### PR TITLE
Fixing graphs when browser TZ is different than Store

### PR DESCRIPTION
**Pull request by cklosowski**
This does a couple things:
1. Instead of passing Timestamps into ChartJS as the XAxes, it uses localized time strings, adjusted for timezone.
2. In order to remain backwards compatible, it adjusts any timestamp passed into the data parser for the graphing, for timezones instead.

### CODE REVIEW

**Comment by cklosowski** [comment]
Before Fix:
image

After Fix:
image

**Review by robincornett — CHANGES_REQUESTED** [review]
I think this is working but the unit tests are expecting different array values:

> 1) EDD\Reports\Data\Charts\v2\Dataset_Tests::test_parse_data_for_output_should_return_single_axis_keyed_data_for_single_level_non_pie_data
> Failed asserting that two arrays are equal.
> Expected
> Actual
> @@ @@
>  Array (
>      0 => Array (
> -        'x' => 40000
> +        'x' => '1970-01-01 00:00:40'
>      )
>      1 => Array (
> -        'x' => 20000
> +        'x' => '1970-01-01 00:00:20'
>      )
>      2 => Array (
> -        'x' => 30000
> +        'x' => '1970-01-01 00:00:30'
>      )
>      3 => Array (
> -        'x' => 10000
> +        'x' => '1970-01-01 00:00:10'
>      )
>  )
>  
> /tmp/wordpress-tests-lib/includes/abstract-testcase.php:685
> /tmp/ZqgBNQvGvmVXpcQsanLVYOl24mDcJ81S/tests/reports/data/charts/v2/tests-dateset.php:156
> /tmp/ZqgBNQvGvmVXpcQsanLVYOl24mDcJ81S/vendor/phpunit/phpunit/phpunit:51
>  
> 2) EDD\Reports\Data\Charts\v2\Dataset_Tests::test_parse_data_for_output_should_return_double_axis_keyed_data_for_double_level_non_pie_data
> Failed asserting that two arrays are equal.
> Expected
> Actual
> @@ @@
>  Array (
>      0 => Array (
> -        'x' => 40000
> +        'x' => '1970-01-01 00:00:40'
>          'y' => 1
>      )
>      1 => Array (
> -        'x' => 20000
> +        'x' => '1970-01-01 00:00:20'
>          'y' => 2
>      )
>      2 => Array (
> -        'x' => 30000
> +        'x' => '1970-01-01 00:00:30'
>          'y' => 3
>      )
>      3 => Array (
> -        'x' => 10000
> +        'x' => '1970-01-01 00:00:10'
>          'y' => 4
>      )
>  )
>  
> /tmp/wordpress-tests-lib/includes/abstract-testcase.php:685
> /tmp/ZqgBNQvGvmVXpcQsanLVYOl24mDcJ81S/tests/reports/data/charts/v2/tests-dateset.php:189
> /tmp/ZqgBNQvGvmVXpcQsanLVYOl24mDcJ81S/vendor/phpunit/phpunit/phpunit:51

**Comment by robincornett** [comment]
Just pushed up a commit to merge release/3.1 back into this branch and resolve the merge conflict.

**Review by robincornett — APPROVED** [review]

**Comment by JJJ** [comment]
🎉🎉🎉🎉🎉

**Pull request merged**
