### PR TITLE
Updating scripts for backwards compatibilty

### PR DESCRIPTION
**Pull request by cklosowski**
This changes the `package.json` to update with some more recent versions of the necessary node modules.

The level we were working on in the previous PR was only working for WP 6.0, this works back to WP 4.9.19

### CODE REVIEW

**Comment by spencerfinnell** [comment]
@cklosowski what did you find wrong in < 6.0? I'm not seeing anything stand out when I test older versions on the previous `update/3.0-deps` branch.

**Comment by robincornett** [comment]
@spencerfinnell we encountered a backbone JS error in WP 5.8 which prevented parts of the order details templates from loading/rendering.

**Comment by robincornett** [comment]
@spencerfinnell here is the specific error (WP 5.8):

```
Uncaught TypeError: (intermediate value)(intermediate value).model is not a constructor
    at n._prepareModel (backbone.min.js?ver=1.4.0:2:12306)
    at n.set (backbone.min.js?ver=1.4.0:2:9432)
    at n.add (backbone.min.js?ver=1.4.0:2:8582)
    at edd-admin-orders.js?ver=1655376304:1:105452
    at Array.forEach (<anonymous>)
    at edd-admin-orders.js?ver=1655376304:1:105418
    at edd-admin-orders.js?ver=1655376304:1:105531
    at edd-admin-orders.js?ver=1655376304:1:111615
    at edd-admin-orders.js?ver=1655376304:1:111619
```

**Comment by cklosowski** [comment]
I need to merge this in, it's preventing me from handling some reporting JS fixes.

**Pull request merged**
