### PR TITLE
Close the 'More' dialog when clicking outside of it.

### LINKED ISSUE #8478: 3.0 - Dismiss "More" Filter in Orders
### Expected behavior
I expect to be able to dismiss the menu that shows after clicking "More" by clicking outside of that area

### Actual behavior
Clicking outside of the menu does not dismiss the menu.  Instead I have to click back on the "More" button to dismiss

### Steps to reproduce the behavior
1) Orders > More  (filter bar)
2) Try to dismiss the menu by clicking outside modal

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 3.0

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by cklosowski**
Fixes #8478 

Proposed Changes:
1. Adds an event listener on the document and when clicking any element outside of the `#edd-advanced-filters` element, it closes.

### CODE REVIEW

**Review by robincornett — COMMENTED** [review]
This works, but can we also add a `keydown` event listener for the Escape key please?

**Comment by cklosowski** [comment]
@robincornett Yeah that should be just fine.

**Comment by cklosowski** [comment]
@robincornett Okay this is ready for another round of testing. Please test click events in and outside of the overlay, as well as the esc key, since I changed the logic to be DRY we need to test those again to ensure I haven't broken the existing toggles.

**Review by robincornett — CHANGES_REQUESTED** [review]
With the current code, clicking anywhere on the orders screen opens the "More" overlay if it's closed.

**Comment by cklosowski** [comment]
Fixed in https://github.com/awesomemotive/easy-digital-downloads/pull/9419/commits/b13cfd58814cc8b1394dafd1b0d355ae80cc15f9 @robincornett

**Review by robincornett — APPROVED** [review]

**Pull request merged**
