### PR TITLE
Improved looping through date range in the Stats API

### LINKED ISSUE #9435: Stats API is crashing the site when Time zone is UTC +
### Expected behavior
Accessing the API via /edd-api/stats?type=earnings&date=range&startdate=20220905&enddate=20220906 to work

### Actual behavior
The website/database crashes. Stuck in a constant loading.

### Steps to reproduce the behavior 
1) In your WordPress settings change Timezone to anything UTC +. It can be +30 or +9
2) Check the API endpoint as above

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): main

WordPress Version: latest

Any other relevant information:
Issue discovered in a ticket here https://secure.helpscout.net/conversation/2004134129/2156206?folderId=5762562
Reverting back to EDD 3.0.3 seems to work.

### PR DESCRIPTION
**Pull request by zkawesome**
Fixes #9435

Proposed Changes:
- I have improved how the date range is looped over in the Stats API. Current integration had a `while` loop that could get stuck in certain situations. I have replaced the logic with Carbon methods. 
- Database is now using UTC converted dates and dates returned in the array are in a localized format.
- Documented code a little better.

### CODE REVIEW

**Review by robincornett — COMMENTED** [review]
This is still not working for me--setting my time to UTC+4 results in the API request spinning endlessly. I haven't gotten an error or official timeout yet.

**Comment by mihaijoldis** [comment]
Same thing to me with a request like this:

`https://www.localhost.com/edd/edd-api/stats?token=fb99cd0e4f164ab84378b3356fe19d31&key=2822e49cb389b7a6d485488ca8d0a165&type=earnings&date=range&startdate=20220905&enddate=20220906

**Review by robincornett — APPROVED** [review]
I think my initial test was with my server still hung up in the bug reported in the issue. I restarted the server and the request works correctly with UTC+4 and New York.

**Review by mihaijoldis — APPROVED** [review]

**Comment by cklosowski** [comment]
@mihaijoldis @robincornett Most local servers don't have multiple threads for processing requests like that and are also configured with longer TTLs on the workers, so it is very likely that the 'replication' was still holding the thread hostage.

**Review by cklosowski — APPROVED** [review]

**Pull request merged**
